title: PoC: Parquet file generator based on Kappa architecture
description: PoC: Parquet file generator based on Kappa architecture
baseurl: "/poc-kappa-parquet-file-generator"
url: "https://tisnik.github.io"

heading_anchors: true
search_enabled: false

aux_links:
  "Github repository":
    - "https://github.com/tisnik/poc-kappa-parquet-file-generator"

footer_content: "Copyright &copy; 2020 Pavel Tisnovsky</a>"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
